#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Reservation
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Mini_Project")]
	public partial class Train_ReservationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertCustomerID(CustomerID instance);
    partial void UpdateCustomerID(CustomerID instance);
    partial void DeleteCustomerID(CustomerID instance);
    partial void InsertTrain_Book(Train_Book instance);
    partial void UpdateTrain_Book(Train_Book instance);
    partial void DeleteTrain_Book(Train_Book instance);
    partial void InsertTrain_Status(Train_Status instance);
    partial void UpdateTrain_Status(Train_Status instance);
    partial void DeleteTrain_Status(Train_Status instance);
    #endregion
		
		public Train_ReservationDataContext() : 
				base(global::Train_Reservation.Properties.Settings.Default.Mini_ProjectConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Train_ReservationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Train_ReservationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Train_ReservationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Train_ReservationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<BookedTicket> BookedTickets
		{
			get
			{
				return this.GetTable<BookedTicket>();
			}
		}
		
		public System.Data.Linq.Table<CustomerID> CustomerIDs
		{
			get
			{
				return this.GetTable<CustomerID>();
			}
		}
		
		public System.Data.Linq.Table<Train_Book> Train_Books
		{
			get
			{
				return this.GetTable<Train_Book>();
			}
		}
		
		public System.Data.Linq.Table<Train_Status> Train_Status
		{
			get
			{
				return this.GetTable<Train_Status>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BookedTickets")]
	public partial class BookedTicket
	{
		
		private string _BookingID;
		
		private string _TrainNumber;
		
		private string _Class;
		
		private string _PassengerName;
		
		private System.Nullable<decimal> _PassengerAge;
		
		private string _PassengerGender;
		
		private System.Nullable<bool> _IsCanceled;
		
		private string _Username;
		
		public BookedTicket()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingID", DbType="NVarChar(100)")]
		public string BookingID
		{
			get
			{
				return this._BookingID;
			}
			set
			{
				if ((this._BookingID != value))
				{
					this._BookingID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainNumber", DbType="NVarChar(100)")]
		public string TrainNumber
		{
			get
			{
				return this._TrainNumber;
			}
			set
			{
				if ((this._TrainNumber != value))
				{
					this._TrainNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="NVarChar(100)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this._Class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassengerName", DbType="VarChar(15)")]
		public string PassengerName
		{
			get
			{
				return this._PassengerName;
			}
			set
			{
				if ((this._PassengerName != value))
				{
					this._PassengerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassengerAge", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> PassengerAge
		{
			get
			{
				return this._PassengerAge;
			}
			set
			{
				if ((this._PassengerAge != value))
				{
					this._PassengerAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassengerGender", DbType="VarChar(5)")]
		public string PassengerGender
		{
			get
			{
				return this._PassengerGender;
			}
			set
			{
				if ((this._PassengerGender != value))
				{
					this._PassengerGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCanceled", DbType="Bit")]
		public System.Nullable<bool> IsCanceled
		{
			get
			{
				return this._IsCanceled;
			}
			set
			{
				if ((this._IsCanceled != value))
				{
					this._IsCanceled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(100)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerID")]
	public partial class CustomerID : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _C_ID;
		
		private System.Nullable<decimal> _C_PSWD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnC_IDChanging(decimal value);
    partial void OnC_IDChanged();
    partial void OnC_PSWDChanging(System.Nullable<decimal> value);
    partial void OnC_PSWDChanged();
    #endregion
		
		public CustomerID()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_ID", DbType="Decimal(5,0) NOT NULL", IsPrimaryKey=true)]
		public decimal C_ID
		{
			get
			{
				return this._C_ID;
			}
			set
			{
				if ((this._C_ID != value))
				{
					this.OnC_IDChanging(value);
					this.SendPropertyChanging();
					this._C_ID = value;
					this.SendPropertyChanged("C_ID");
					this.OnC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_PSWD", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> C_PSWD
		{
			get
			{
				return this._C_PSWD;
			}
			set
			{
				if ((this._C_PSWD != value))
				{
					this.OnC_PSWDChanging(value);
					this.SendPropertyChanging();
					this._C_PSWD = value;
					this.SendPropertyChanged("C_PSWD");
					this.OnC_PSWDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Train_Book")]
	public partial class Train_Book : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Sl_No;
		
		private string _Train_No;
		
		private string _Train_Name;
		
		private string _Arrival_Time;
		
		private string _Departure_Time;
		
		private string _Travel_Duration;
		
		private string _Class;
		
		private System.Nullable<int> _Total_Berth;
		
		private System.Nullable<int> _Available_Berth;
		
		private string _From;
		
		private string _To;
		
		private string _Runs_On;
		
		private System.Nullable<decimal> _Price;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSl_NoChanging(decimal value);
    partial void OnSl_NoChanged();
    partial void OnTrain_NoChanging(string value);
    partial void OnTrain_NoChanged();
    partial void OnTrain_NameChanging(string value);
    partial void OnTrain_NameChanged();
    partial void OnArrival_TimeChanging(string value);
    partial void OnArrival_TimeChanged();
    partial void OnDeparture_TimeChanging(string value);
    partial void OnDeparture_TimeChanged();
    partial void OnTravel_DurationChanging(string value);
    partial void OnTravel_DurationChanged();
    partial void OnClassChanging(string value);
    partial void OnClassChanged();
    partial void OnTotal_BerthChanging(System.Nullable<int> value);
    partial void OnTotal_BerthChanged();
    partial void OnAvailable_BerthChanging(System.Nullable<int> value);
    partial void OnAvailable_BerthChanged();
    partial void OnFromChanging(string value);
    partial void OnFromChanged();
    partial void OnToChanging(string value);
    partial void OnToChanged();
    partial void OnRuns_OnChanging(string value);
    partial void OnRuns_OnChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Train_Book()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sl_No", DbType="Decimal(20,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Sl_No
		{
			get
			{
				return this._Sl_No;
			}
			set
			{
				if ((this._Sl_No != value))
				{
					this.OnSl_NoChanging(value);
					this.SendPropertyChanging();
					this._Sl_No = value;
					this.SendPropertyChanged("Sl_No");
					this.OnSl_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Train_No", DbType="NVarChar(100)")]
		public string Train_No
		{
			get
			{
				return this._Train_No;
			}
			set
			{
				if ((this._Train_No != value))
				{
					this.OnTrain_NoChanging(value);
					this.SendPropertyChanging();
					this._Train_No = value;
					this.SendPropertyChanged("Train_No");
					this.OnTrain_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Train_Name", DbType="NVarChar(100)")]
		public string Train_Name
		{
			get
			{
				return this._Train_Name;
			}
			set
			{
				if ((this._Train_Name != value))
				{
					this.OnTrain_NameChanging(value);
					this.SendPropertyChanging();
					this._Train_Name = value;
					this.SendPropertyChanged("Train_Name");
					this.OnTrain_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arrival_Time", DbType="NVarChar(50)")]
		public string Arrival_Time
		{
			get
			{
				return this._Arrival_Time;
			}
			set
			{
				if ((this._Arrival_Time != value))
				{
					this.OnArrival_TimeChanging(value);
					this.SendPropertyChanging();
					this._Arrival_Time = value;
					this.SendPropertyChanged("Arrival_Time");
					this.OnArrival_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departure_Time", DbType="NVarChar(50)")]
		public string Departure_Time
		{
			get
			{
				return this._Departure_Time;
			}
			set
			{
				if ((this._Departure_Time != value))
				{
					this.OnDeparture_TimeChanging(value);
					this.SendPropertyChanging();
					this._Departure_Time = value;
					this.SendPropertyChanged("Departure_Time");
					this.OnDeparture_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Travel_Duration", DbType="NVarChar(50)")]
		public string Travel_Duration
		{
			get
			{
				return this._Travel_Duration;
			}
			set
			{
				if ((this._Travel_Duration != value))
				{
					this.OnTravel_DurationChanging(value);
					this.SendPropertyChanging();
					this._Travel_Duration = value;
					this.SendPropertyChanged("Travel_Duration");
					this.OnTravel_DurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="NVarChar(50)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this.OnClassChanging(value);
					this.SendPropertyChanging();
					this._Class = value;
					this.SendPropertyChanged("Class");
					this.OnClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Berth", DbType="Int")]
		public System.Nullable<int> Total_Berth
		{
			get
			{
				return this._Total_Berth;
			}
			set
			{
				if ((this._Total_Berth != value))
				{
					this.OnTotal_BerthChanging(value);
					this.SendPropertyChanging();
					this._Total_Berth = value;
					this.SendPropertyChanged("Total_Berth");
					this.OnTotal_BerthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available_Berth", DbType="Int")]
		public System.Nullable<int> Available_Berth
		{
			get
			{
				return this._Available_Berth;
			}
			set
			{
				if ((this._Available_Berth != value))
				{
					this.OnAvailable_BerthChanging(value);
					this.SendPropertyChanging();
					this._Available_Berth = value;
					this.SendPropertyChanged("Available_Berth");
					this.OnAvailable_BerthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[From]", Storage="_From", DbType="NVarChar(100)")]
		public string From
		{
			get
			{
				return this._From;
			}
			set
			{
				if ((this._From != value))
				{
					this.OnFromChanging(value);
					this.SendPropertyChanging();
					this._From = value;
					this.SendPropertyChanged("From");
					this.OnFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[To]", Storage="_To", DbType="NVarChar(100)")]
		public string To
		{
			get
			{
				return this._To;
			}
			set
			{
				if ((this._To != value))
				{
					this.OnToChanging(value);
					this.SendPropertyChanging();
					this._To = value;
					this.SendPropertyChanged("To");
					this.OnToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Runs_On", DbType="NVarChar(100)")]
		public string Runs_On
		{
			get
			{
				return this._Runs_On;
			}
			set
			{
				if ((this._Runs_On != value))
				{
					this.OnRuns_OnChanging(value);
					this.SendPropertyChanging();
					this._Runs_On = value;
					this.SendPropertyChanged("Runs_On");
					this.OnRuns_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Train_Status")]
	public partial class Train_Status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Sl_No;
		
		private string _Train_No;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSl_NoChanging(decimal value);
    partial void OnSl_NoChanged();
    partial void OnTrain_NoChanging(string value);
    partial void OnTrain_NoChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Train_Status()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sl_No", DbType="Decimal(5,0) NOT NULL", IsPrimaryKey=true)]
		public decimal Sl_No
		{
			get
			{
				return this._Sl_No;
			}
			set
			{
				if ((this._Sl_No != value))
				{
					this.OnSl_NoChanging(value);
					this.SendPropertyChanging();
					this._Sl_No = value;
					this.SendPropertyChanged("Sl_No");
					this.OnSl_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Train_No", DbType="NVarChar(100)")]
		public string Train_No
		{
			get
			{
				return this._Train_No;
			}
			set
			{
				if ((this._Train_No != value))
				{
					this.OnTrain_NoChanging(value);
					this.SendPropertyChanging();
					this._Train_No = value;
					this.SendPropertyChanged("Train_No");
					this.OnTrain_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
